export const NOVO_PROJETO = 'NOVO_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
export const DEFINIR_PROJETO = 'DEFINIR_PROJETO'

export const NOVO_TAREFA = 'NOVO_TAREFA'
export const ALTERA_TAREFA = 'ALTERA_TAREFA'
export const EXCLUIR_TAREFA = 'EXCLUIR_TAREFA'
export const DEFINIR_TAREFA = 'DEFINIR_TAREFA'


export const NOTIFICAR = 'NOTIFICAR'